name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Możesz dostosować wersję Node.js

      # Install dependencies for backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build --prod
        env:
          # Ustaw zmienne środowiskowe używane przez Angular CLI jeśli potrzebujesz

      # Move frontend build to backend/public (or any static serve directory)
      - name: Move frontend build to backend directory
        run: |
          mv frontend/dist/* backend/public/

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: dotlaw-akademia # Nazwa Twojej aplikacji w Azure
          slot-name: Production
          package: backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A729626A7A98430080D68F040317FF05 }}
