name: Build and Deploy Node.js + Angular app to Azure Web App - dotlaw-akademia

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js version for backend
      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      # Install and build backend
      - name: Install backend dependencies and build
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present

      # Set up Node.js version for frontend
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Install frontend dependencies including @stripe/stripe-js with legacy-peer-deps
      - name: Install frontend dependencies with legacy peer deps
        run: |
          cd frontend
          npm install --legacy-peer-deps
        shell: pwsh

      # Install @stripe/stripe-js explicitly
      - name: Install @stripe/stripe-js explicitly
        run: |
          cd frontend
          npm install @stripe/stripe-js
        shell: pwsh

      # Build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm run build --prod
        shell: pwsh

      # Move frontend build output to backend/public directory
      - name: Move frontend build to backend/public directory
        run: |
          Move-Item -Path frontend/dist/* -Destination backend/public/
        shell: pwsh

      # Package the backend with frontend static files for deployment
      - name: Package backend and frontend for deployment
        run: |
          Compress-Archive -Path backend/* -DestinationPath ready_for_deployment.zip
        shell: pwsh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ready_for_deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-package

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dotlaw-akademia'
          slot-name: 'Production'
          package: ready_for_deployment.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A729626A7A98430080D68F040317FF05 }}
